name: deploy-orders

on:
  push:
    branches:
      - main
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd orders && docker build -t denilgabani/orders .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PWD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PWD: ${{secrets.DOCKER_PWD}}
      - run: docker push denilgabani/orders
